DATA_ROOT = "data/"

PURGES = 'PURGES'
ASSASSINATIONS = 'ASSASSINATIONS'
GOVERNMENT_CRISES = 'GOVERNMENT CRISES'
GUERRILLA_WARFARE = 'GUERRILLA WARFARE'
GENERAL_STRIKES = 'GENERAL STRIKES'
RIOTS = 'RIOTS'
REVOLUTIONS = 'REVOLUTIONS'
AG_DEMO = 'AG DEMO'
NONE = 'NONE'

TAGS = {PURGES: 1, ASSASSINATIONS: 2, GOVERNMENT_CRISES: 3,
        GUERRILLA_WARFARE: 4, GENERAL_STRIKES: 5, RIOTS: 6,
        REVOLUTIONS: 7, AG_DEMO: 8, NONE: 9}

R_TAGS = {1: PURGES, 2: ASSASSINATIONS, 3: GOVERNMENT_CRISES,
          4: GUERRILLA_WARFARE, 5: GENERAL_STRIKES, 6: RIOTS,
          7: REVOLUTIONS, 8: AG_DEMO, 9: NONE}

ARTICLE = 2

